import type { Practice } from "./types";

export const practices: Practice[] = [
  {
    id: "P01",
    fictionalName: "Clínica Dental Norte",
    city: "Monterrey",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "ASSUMPTION",
        evidence: "Header result is seeded for the pilot and not independently verified.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains an SPF policy.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "COULD_NOT_CHECK",
        evidence: "Demo adapter returned insufficient evidence.",
        consequential: false,
      },
    ],
  },
  {
    id: "P02",
    fictionalName: "Sonrisa Roma",
    city: "Mexico City",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "CONFIRMED",
        evidence: "Simulated response includes the expected baseline headers.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value; live verification has not occurred.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains a DMARC policy.",
        consequential: false,
      },
    ],
  },
  {
    id: "P03",
    fictionalName: "Dental Sur MX",
    city: "Mexico City",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "COULD_NOT_CHECK",
        evidence: "Simulated endpoint timeout; no conclusion is shown.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains an SPF policy.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "ASSUMPTION",
        evidence: "Seeded value awaiting a controlled verification step.",
        consequential: false,
      },
    ],
  },
  {
    id: "P04",
    fictionalName: "Clínica Molar",
    city: "Puebla",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value; live verification has not occurred.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains an SPF policy.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "COULD_NOT_CHECK",
        evidence: "Simulated DNS adapter returned no usable result.",
        consequential: false,
      },
    ],
  },
  {
    id: "P05",
    fictionalName: "Dental Centro",
    city: "Querétaro",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "CONFIRMED",
        evidence: "Simulated response includes the expected baseline headers.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value; live verification has not occurred.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains a DMARC policy.",
        consequential: false,
      },
    ],
  },
  {
    id: "P06",
    fictionalName: "Sonrisa Coyoacán",
    city: "Mexico City",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "CONFIRMED",
        evidence: "Simulated response includes the expected baseline headers.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "COULD_NOT_CHECK",
        evidence: "Simulated DNS adapter timed out.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value awaiting controlled verification.",
        consequential: false,
      },
    ],
  },
  {
    id: "P07",
    fictionalName: "Dental Valle",
    city: "San Pedro Garza García",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value; not independently verified.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains an SPF policy.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains a DMARC policy.",
        consequential: false,
      },
    ],
  },
  {
    id: "P08",
    fictionalName: "Clínica Prisma",
    city: "Guadalajara",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "COULD_NOT_CHECK",
        evidence: "The simulated target did not return enough evidence.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value; live verification has not occurred.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains a DMARC policy.",
        consequential: false,
      },
    ],
  },
  {
    id: "P09",
    fictionalName: "Dental Reforma",
    city: "Mexico City",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "CONFIRMED",
        evidence: "Simulated response includes the expected baseline headers.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains an SPF policy.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value awaiting controlled verification.",
        consequential: false,
      },
    ],
  },
  {
    id: "P10",
    fictionalName: "Sonrisa Lindavista",
    city: "Mexico City",
    dataLabel: "SIMULATED",
    findings: [
      {
        control: "HTTPS",
        label: "HTTPS",
        state: "CONFIRMED",
        evidence: "Simulated public check indicates HTTPS is enabled.",
        consequential: false,
      },
      {
        control: "HEADERS",
        label: "Security headers",
        state: "ASSUMPTION",
        evidence: "Seeded pilot value; live verification has not occurred.",
        consequential: false,
      },
      {
        control: "SPF",
        label: "SPF",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains an SPF policy.",
        consequential: false,
      },
      {
        control: "DMARC",
        label: "DMARC",
        state: "CONFIRMED",
        evidence: "Simulated DNS result contains a DMARC policy.",
        consequential: false,
      },
      {
        control: "EFIRMA_HYGIENE",
        label: "Fiscal-identity concern",
        state: "ESCALATE",
        evidence:
          "Simulated report indicates possible fiscal-identity misuse. No credential or e.firma material is collected.",
        consequential: true,
      },
    ],
  },
];
